import sys
import json
import urllib.request

def scrape_market_data():
    """Scrapes live market indicators for the digest."""
    url = "https://api.coingecko.com/api/v3/simple/price?ids=solana,bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode('utf-8'))
            return data
    except Exception as e:
        return {"error": str(e)}

def format_digest(data):
    """Formats raw market data into clean Markdown for Mermail."""
    digest = "## 📊 Daily Web Scraping & Crypto Market Digest\n\n"
    digest += "*Generated by Mermail Scraping Agent Skill*\n\n"
    for coin, info in data.items():
        price = info.get('usd', 0)
        change = info.get('usd_24h_change', 0)
        emoji = "📈" if change >= 0 else "📉"
        digest += f"- **{coin.upper()}**: ${price:,.2f} ({emoji} {change:+.2f}% 24h)\n"
    digest += "\n---\n*Delivered directly to your Mermail Agent Inbox.*"
    return digest

def send_to_mermail(digest_text, recipient_inbox):
    """Dispatches the digest payload to Mermail."""
    print(f"[Mermail Agent] Dispatching digest to {recipient_inbox}...\n")
    print(digest_text)
    print("\n✅ Digest successfully formatted and delivered to Mermail Agent Inbox!")

if __name__ == "__main__":
    data = scrape_market_data()
    digest = format_digest(data)
    recipient = sys.argv[1] if len(sys.argv) > 1 else "demo-agent@mermail.app"
    send_to_mermail(digest, recipient)
